### ISSUE TITLE
python-pycryptodome does not provide the required Cryptodome library, python-pycryptodomex does

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-rosbag#3]
I see `python-crypto` in deps, and:
```
$ pacman -Qi python-crypto
Name            : python-pycryptodome
Version         : 3.9.9-3
Description     : Collection of cryptographic algorithms and protocols, implemented for use from Python 3.
Architecture    : x86_64
URL             : https://www.pycryptodome.org/
```

So it _looks_ like the right thing, but:
```
]$ rosbag
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/rosbag", line 34, in <module>
    import rosbag
  File "/opt/ros/melodic/lib/python3.9/site-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/opt/ros/melodic/lib/python3.9/site-packages/rosbag/bag.py", line 53, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'
```
I believe I ran into this the last time as [this](https://github.com/DP-3T/reference_implementation/issues/1) was still in my search suggestions. After `pip install --user pycryptodomex`, all is well. Perhaps [this SO post](https://stackoverflow.com/questions/48155294/what-is-pycryptodomex-and-how-does-it-differ-from-pycryptodome) sheds light on the difference between the two. Should we be using `python-cryptodomex` instead of `python-crypto`? Or is this on my end?

**Comment by jwhendy** [comment]
Update: doesn't [this line](https://github.com/ros/ros_comm/blob/melodic-devel/tools/rosbag/src/rosbag/bag.py#L53) importing `Cryptodome` explicitly suggest that it _can't_ by `python-crypto` that we want? The latter appears only to provide `Crypto`. If so, I think this should switch to `python-cryptodomex`.

**Comment by jwhendy** [comment]
For what it's worth, removing my `pip --user` installed version and swapping the packages in `PKGBUILD` works for me. Once someone can take a look at the links above, I can do a PR or just push it.

**Comment by bionade24** [comment]
> Update: doesn't [this line](https://github.com/ros/ros_comm/blob/melodic-devel/tools/rosbag/src/rosbag/bag.py#L53) importing `Cryptodome` explicitly suggest that it _can't_ by `python-crypto` that we want? The latter appears only to provide `Crypto`. If so, I think this should switch to `python-cryptodomex`.

Are you sure the right package isn't https://archlinux.org/packages/community/x86_64/python-pycryptodome/ ?
If you make a PR for this package after you validated that it runs, that would be nice.

**Comment by jwhendy** [comment]
@bionade24 that is the package (correct in my title, though I was initially confused by the pacman output). The `PKGBUILD` technically lists `python-crypto` in the `depends` which is provided by the package you found, `python-pycryptodome`. `python-crypto`==`python-pycryptodome`, which provides `Crypto`, but not `Cryptodome`, which is what `rosbag` expects. Again, I could be wrong, but I take this to be us wanting `python-pycryptodomex` instead.
